(function () {
  const R=window.React, RD=window.ReactDOM, h=R&&R.createElement, root=document.getElementById('simple-root');
  const KEY='__dc_superuser_auth__';
  if(!R||!RD||!h){root.textContent='Unable to load the room viewer. Check the network connection and reload.';return;}
  const {useEffect,useMemo,useState}=R;
  async function api(path,options={}){const response=await fetch('./'+path,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.message||`Request failed (${response.status})`),{body});return body;}
  async function signIn(){try{const fresh=await api('api/discord/admin-token',{method:'POST'});localStorage.setItem(KEY,JSON.stringify(fresh));return fresh.token;}catch(error){const saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(!saved.token)throw error;const fresh=await api('api/collections/_superusers/auth-refresh',{method:'POST',headers:{Authorization:saved.token}});localStorage.setItem(KEY,JSON.stringify(fresh));return fresh.token;}}
  const c=(tag,props,...children)=>h(tag,props,...children);
  const time=(ts)=>window.DCTime?.absolute(ts)||ts||'Unknown time'; const relative=(ts,now)=>window.DCTime?.relative(ts,now)||''; const day=(ts)=>window.DCTime?.bangkokDay(ts)||String(ts||'').slice(0,10); const label=(date)=>window.DCTime?.dayLabel(date)||date;
  function ThreadRow({thread,active,choose,guild}) { return c('button',{type:'button','data-entity-id':thread.id,onClick:()=>choose(thread,'thread',guild),className:'flex w-full items-center gap-1 py-1.5 pl-8 pr-3 text-left text-sm hover:bg-slate-700 '+(active?.id===thread.id?'bg-slate-700 font-semibold text-white':'text-slate-400')},c('span',{className:'w-5 text-center'},'↳'),c('span',{className:'min-w-0 flex-1 truncate'},thread.name)); }
  function ChannelRow({channel,active,choose,guild}) { return c('div',{key:channel.id},c('button',{type:'button','data-entity-id':channel.id,onClick:()=>choose(channel,'channel',guild),className:'flex w-full items-center gap-1 px-3 py-1.5 text-left text-sm hover:bg-slate-700 '+(active?.id===channel.id?'bg-slate-700 font-semibold text-white':'text-slate-300')},c('span',{className:'w-5 text-center text-slate-400'},'#'),c('span',{className:'min-w-0 flex-1 truncate'},channel.name),channel.imported_count?c('span',{className:'text-[10px] tabular-nums text-slate-500'},channel.imported_count):null),channel.threads.map(thread=>c(ThreadRow,{key:thread.id,thread,active,choose,guild}))); }
  function GuildSection({guild,active,choose}) { return c('section',{key:guild.id,className:'mb-4'},c('h2',{className:'px-4 pb-1 text-[11px] font-bold uppercase tracking-wide text-slate-400'},guild.name),guild.channels.map(channel=>c(ChannelRow,{key:channel.id,channel,active,choose,guild:guild.name}))); }
  function RoomTree({tree,active,query,setQuery,choose}) {
    const visible=tree.map(g=>({...g,channels:g.channels.filter(channel=>!query||[channel.name,...channel.threads.map(thread=>thread.name)].join(' ').toLowerCase().includes(query.toLowerCase()))})).filter(g=>g.channels.length);
    const content=visible.length?visible.map(guild=>c(GuildSection,{key:guild.id,guild,active,choose})):c('p',{className:'px-4 text-sm text-slate-500'},query?'No matching rooms.':'No rooms discovered yet.');
    const facts=tree.flatMap(guild=>guild.channels.map(channel=>({guild:guild.name,name:channel.name,id:channel.id,count:channel.imported_count||0})));
    const groundTruth=c('details',{className:'mt-auto border-t border-slate-700 p-3'},c('summary',{className:'cursor-pointer text-xs font-semibold text-slate-300'},'Ground truth / backfill coverage'),c('p',{className:'mt-2 text-xs leading-5 text-slate-400'},'Counts are the stored PocketBase records. Re-run backfill from Dashboard to reconcile the selected rooms.'),c('table',{className:'mt-2 w-full text-left text-[11px] text-slate-400'},c('thead',null,c('tr',{className:'text-slate-500'},c('th',null,'Room'),c('th',{className:'text-right'},'Stored'))),c('tbody',null,facts.map(row=>c('tr',{key:row.id,className:'border-t border-slate-700/70'},c('td',{className:'max-w-[175px] truncate py-1',title:row.guild+' / '+row.name+' · '+row.id},row.guild+' / '+row.name),c('td',{className:'py-1 text-right tabular-nums'},row.count))))));
    return c('aside',{id:'simple-tree',className:'scrollbar flex min-h-0 w-72 shrink-0 flex-col overflow-y-auto bg-nav text-slate-200'},c('div',{className:'border-b border-slate-700 px-4 py-4'},c('div',{className:'text-sm font-bold text-white'},'Discord Archive'),c('p',{className:'mt-1 text-xs text-slate-400'},'Rooms discovered from your model')),c('div',{className:'px-3 py-3'},c('input',{value:query,onChange:e=>setQuery(e.target.value),placeholder:'Find a channel',className:'w-full rounded-md border border-slate-600 bg-rail px-3 py-2 text-sm text-white placeholder:text-slate-500'})),c('nav',{className:'pb-5','aria-label':'Guilds, channels, and threads'},content),groundTruth);
  }
  function Feed({messages,active,state,now}) {
    const groups=useMemo(()=>messages.reduce((out,message)=>{const key=day(message.ts);(out[key]||=[]).push(message);return out;},{}),[messages]);
    if(!Object.keys(groups).length)return c('div',{className:'mx-auto mt-20 max-w-md text-center'},c('p',{id:'simple-status',className:'text-sm text-slate-400',role:'status'},state),c('h2',{className:'mt-3 text-lg font-bold text-white'},active?'No imported messages in this room':'Your room list will appear here'),c('p',{className:'mt-2 text-sm leading-6 text-slate-400'},active?'Choose a configured room or use the dashboard to backfill it.':'The channel model is loading from PocketBase.'));
    return c('div',null,c('p',{id:'simple-status',className:'mb-5 text-sm text-slate-400',role:'status'},state),Object.entries(groups).map(([date,items])=>c('section',{key:date},c('div',{className:'sticky top-0 z-10 my-5 flex items-center gap-3 bg-slate-950 py-2'},c('span',{className:'h-px flex-1 bg-slate-800'}),c('h2',{className:'text-xs font-semibold text-slate-400'},label(date)),c('span',{className:'h-px flex-1 bg-slate-800'})),items.map(message=>c('article',{key:message.id||message.message_id,className:'flex gap-3 py-2'},c('div',{className:'grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-700 text-xs font-bold text-slate-200'},(message.author_name||'?').slice(0,2).toUpperCase()),c('div',{className:'min-w-0'},c('div',{className:'flex flex-wrap items-baseline gap-x-2'},c('strong',{className:'text-sm text-slate-100'},message.author_name||message.author_id||'Unknown'),c('time',{title:window.DCTime?.iso(message.ts)||message.ts,className:'text-xs text-slate-500'},time(message.ts)),c('span',{className:'text-xs text-slate-600'},relative(message.ts,now))),c('p',{className:'whitespace-pre-wrap break-words text-sm leading-6 text-slate-300'},message.content||'[no text]')))))));
  }
  function App(){
    const [token,setToken]=useState(''),[tree,setTree]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[state,setState]=useState('Connecting through Home Assistant…'),[query,setQuery]=useState(''),[drawer,setDrawer]=useState(false),[now,setNow]=useState(Date.now());
    useEffect(()=>{const interval=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(interval);},[]);
    useEffect(()=>{(async()=>{try{const token=await signIn();setToken(token);const entities=await api('api/dc/channels',{headers:{Authorization:token}});const next=window.DCSimpleTree.buildTree(entities);setTree(next);const first=next.flatMap(g=>g.channels)[0];if(first)setActive({id:first.id,name:first.name,kind:'channel',guild:next[0]?.name||''});setState(`${entities.length} discovered rooms`);}catch(error){setState(error.body?.haUser?`Home Assistant user ${error.body.haUser} is not allowed.`:error.message);}})();},[]);
    useEffect(()=>{if(!token||!active)return;let dead=false;(async()=>{try{setState(`Loading #${active.name}…`);const filter=active.kind==='thread'?`thread_id=${JSON.stringify(active.id)}`:`channel_id=${JSON.stringify(active.id)} && (thread_id='' || thread_id=null)`;const result=await api('api/collections/discord_messages/records?'+new URLSearchParams({page:'1',perPage:'100',sort:'-ts,-message_id',filter}),{headers:{Authorization:token}});if(!dead){setMessages(result.items||[]);setState(`${result.totalItems||0} messages in #${active.name}`);}}catch(error){if(!dead)setState(error.message);}})();return()=>{dead=true};},[token,active]);
    const choose=(node,kind,guild)=>{setActive({id:node.id,name:node.name,kind,guild});setDrawer(false);};
    const navigation=c(RoomTree,{tree,active,query,setQuery,choose});
    return c('div',{className:'flex h-[100dvh] min-w-0 overflow-hidden bg-ink'},c('aside',{className:'hidden w-16 shrink-0 flex-col items-center gap-3 bg-rail py-4 md:flex','aria-label':'Guild rail'},c('a',{href:'./panel.html',title:'Archive dashboard',className:'grid h-10 w-10 place-items-center rounded-xl bg-accent text-sm font-bold text-white'},'DA'),...tree.slice(0,6).map(guild=>c('button',{key:guild.id,type:'button',onClick:()=>guild.channels[0]&&choose(guild.channels[0],'channel',guild.name),title:guild.name,className:'grid h-10 w-10 place-items-center rounded-xl bg-slate-700 text-xs font-bold text-slate-200 hover:bg-slate-600'},guild.name.slice(0,2).toUpperCase()))),c('div',{className:'hidden min-h-0 md:flex'},navigation),drawer?c('div',{className:'fixed inset-0 z-30 bg-black/60 md:hidden',onClick:()=>setDrawer(false)},c('div',{className:'h-full w-80 max-w-[85vw]',onClick:event=>event.stopPropagation()},navigation)):null,c('main',{id:'simple-room',className:'flex min-w-0 flex-1 flex-col bg-slate-950'},c('header',{className:'flex min-h-16 shrink-0 items-center gap-3 border-b border-slate-800 px-4'},c('button',{type:'button',onClick:()=>setDrawer(true),className:'rounded-md p-2 text-slate-300 hover:bg-slate-800 md:hidden','aria-label':'Open channel list'},'☰'),c('div',{className:'min-w-0 flex-1'},c('h1',{className:'truncate text-base font-bold text-white'},active?`${active.kind==='thread'?'↳':'#'} ${active.name}`:'Choose a room'),c('p',{className:'truncate text-xs text-slate-400'},active?`${active.guild} · ${active.id}`:'Guild → channel → thread')),c('a',{href:'./panel.html',className:'hidden rounded-md px-3 py-2 text-sm text-slate-300 hover:bg-slate-800 sm:block'},'Dashboard'),c('a',{href:'./_/',className:'rounded-md bg-accent px-3 py-2 text-sm font-semibold text-white hover:brightness-110'},'Admin')),c('div',{className:'scrollbar min-h-0 flex-1 overflow-y-auto px-4 py-5 sm:px-7'},c(Feed,{messages,active,state,now}))));
  }
  RD.createRoot(root).render(c(App));
})();
